[server]
host = "127.0.0.1"
port = 3000
log_directives = "debug"

[database]
url = "sqlite:db.sqlite"
max_connections = 5
run_db_migrations_on_startup = true # Set to false in production for manual migration control

[oauth]
# ⚠️ SECURITY WARNING: NEVER commit real OAuth secrets to git!
# Use one of these secure methods instead:
# 1. Environment variables: APP_OAUTH_GOOGLE_CLIENT_ID, APP_OAUTH_GOOGLE_CLIENT_SECRET
# 2. Create backend/config/local.toml (git-ignored)
# 3. Create .env file in project root (git-ignored)

# Google OAuth2 Secrets
# google_client_id = ""      # ⚠️ LEAVE EMPTY - set via secure method above
# google_client_secret = ""  # ⚠️ LEAVE EMPTY - set via secure method above
google_redirect_uri = "http://localhost:3000/auth/oauth/google/callback"

# You can add more providers here as needed
# github_client_id = ""
# github_client_secret = ""
# github_redirect_uri = "http://localhost:3000/auth/oauth/github/callback"
