[server]
host = "127.0.0.1"
port = 3000
log_directives = "debug,tower_http=debug,axum=debug"

[database]
url = "sqlite:db.sqlite"
max_connections = 5
run_db_migrations_on_startup = true # Auto-migrate is enabled by default for development

[oauth]
# google_client_id = ""      # ⚠️ LEAVE EMPTY - set via secure method above
# google_client_secret = ""  # ⚠️ LEAVE EMPTY - set via secure method above
google_redirect_uri = "http://localhost:3000/auth/oauth/google/callback"
