[server]
host = "127.0.0.1"
port = 3000
log_directives = "debug,tower_http=debug,axum=debug"

[database]
url = "sqlite:db.sqlite"
max_connections = 5

[jwt]
access_token_expiry_minutes = 16
refresh_token_expiry_days = 128

[oauth]
# ⚠️ SECURITY WARNING: NEVER commit real OAuth secrets to git!
# Use one of these secure methods instead:
# 1. Environment variables (in .env file): APP_OAUTH_GOOGLE_CLIENT_ID, APP_OAUTH_GOOGLE_CLIENT_SECRET
# 2. Create configs.local.toml (git-ignored)

google_client_id = ""      # ⚠️ LEAVE EMPTY - set in configs.local.toml or via environment variable
google_client_secret = ""  # ⚠️ LEAVE EMPTY - set in configs.local.toml or via environment variable
google_redirect_uri = "http://localhost:3000/auth/oauth/google/callback"
