app = "svelaxum"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.prod"

[mounts]
  source = "svelaxum_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true     # wakes the machine up when you visit your URL
  auto_stop_machines = "suspend" # dev: allows fly to stop the machine when idle
  min_machines_running = 0       # dev: allows the count to drop to zero
  # auto_stop_machines = "off"   # prod: don't stop the machine
  # min_machines_running = 1     # prod: ensure that the 1 machine is always on

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "30s"
  method = "GET"
  path = "/api/health"

[[restart]]
  policy = "on-failure"
  retries = 10
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  processes = ["app"]