/**
 * Unified API client codegen script.
 *
 * Replaces the previous two-step pipeline:
 *   1. npx openapi-typescript (CLI) → api.d.ts
 *   2. node scripts/generate-endpoints.js → endpoints.ts
 *
 * Now does both in a single script using the openapi-typescript Node.js API.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import prettier from 'prettier';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const openapiPath = path.resolve(__dirname, '../../openapi.json');
const outputDir = path.join(__dirname, '../src/lib/generated');

if (!fs.existsSync(openapiPath)) {
    console.error(`Error: openapi.json not found at ${openapiPath}`);
    process.exit(1);
}

fs.mkdirSync(outputDir, { recursive: true });

async function formatAndWrite(outputPath, content) {
    const config = await prettier.resolveConfig(outputPath);
    const formatted = await prettier.format(content, {
        ...config,
        filepath: outputPath,
    });
    fs.writeFileSync(outputPath, formatted, 'utf8');
}

// Stage 1: Generate TypeScript type definitions (api.d.ts)
console.log('Generating TypeScript definitions from OpenAPI spec...');

const ast = await openapiTS(new URL(`file://${openapiPath}`), {
    rootTypes: true,
    rootTypesNoSchemaPrefix: true,
});
const typesContent = astToString(ast);

const typesHeader = `/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n`;

const typesPath = path.join(outputDir, 'api.d.ts');
await formatAndWrite(typesPath, typesHeader + typesContent);
console.log(`Generated ${typesPath}`);

// Stage 2: Generate typed endpoint wrappers (endpoints.ts)
console.log('Generating TypeScript endpoints...');

const openapi = JSON.parse(fs.readFileSync(openapiPath, 'utf8'));

const groups = {};
const importedTypes = new Set(['paths']);

for (const [route, pathItem] of Object.entries(openapi.paths)) {
    for (const [method, operation] of Object.entries(pathItem)) {
        if (
            !['get', 'post', 'put', 'delete', 'options', 'head', 'patch', 'trace'].includes(method)
        ) {
            continue;
        }

        // Determine group
        const parts = route
            .replace(/^\/api/, '')
            .split('/')
            .filter(Boolean);
        let groupName = parts[0] || 'general';
        if (groupName === 'api' && parts.length > 1) {
            groupName = parts[1];
        }

        if (!groups[groupName]) {
            groups[groupName] = [];
        }

        let name = operation.operationId;
        if (!name) {
            const cleanRoute = route
                .replace(/\/api\//g, '')
                .replace(/[^a-zA-Z0-9_/]/g, '')
                .split('/')
                .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                .join('');
            name = method + cleanRoute;
        }

        const upperMethod = method.toUpperCase();

        const hasBody =
            operation.requestBody &&
            operation.requestBody.content &&
            operation.requestBody.content['application/json'];
        const bodyRequired = hasBody && operation.requestBody.required !== false;

        const queryParams = operation.parameters
            ? operation.parameters.filter((p) => p.in === 'query')
            : [];
        const hasQuery = queryParams.length > 0;
        const queryRequired = queryParams.some((p) => p.required === true);

        let bodyType = '';
        if (hasBody) {
            const schema = operation.requestBody.content['application/json'].schema;
            if (schema && schema.$ref) {
                const refName = schema.$ref.split('/').pop();
                bodyType = refName;
                importedTypes.add(refName);
            } else {
                bodyType = `paths['${route}']['${method}']['requestBody']['content']['application/json']`;
            }
        }

        const paramsList = [];
        let callArgs = '';

        if (hasBody && hasQuery) {
            paramsList.push(`body${bodyRequired ? '' : '?'}: ${bodyType}`);
            paramsList.push(
                `query${queryRequired ? '' : '?'}: paths['${route}']['${method}']['parameters']['query']`
            );
            paramsList.push(
                `options?: Omit<FetchOptions<paths['${route}']['${method}']>, 'body' | 'params'>`
            );
            callArgs = `{ body, params: { query }, ...options }`;
        } else if (hasBody) {
            paramsList.push(`body${bodyRequired ? '' : '?'}: ${bodyType}`);
            paramsList.push(`options?: Omit<FetchOptions<paths['${route}']['${method}']>, 'body'>`);
            callArgs = `{ body, ...options }`;
        } else if (hasQuery) {
            paramsList.push(
                `query${queryRequired ? '' : '?'}: paths['${route}']['${method}']['parameters']['query']`
            );
            paramsList.push(
                `options?: Omit<FetchOptions<paths['${route}']['${method}']>, 'params'>`
            );
            callArgs = `{ params: { query }, ...options }`;
        } else {
            paramsList.push(`options?: FetchOptions<paths['${route}']['${method}']>`);
            callArgs = `options`;
        }

        groups[groupName].push({
            name,
            route,
            method: upperMethod,
            summary: operation.summary || operation.description,
            params: paramsList.join(', '),
            callArgs,
        });
    }
}

const lines = [];
lines.push(`/**`);
lines.push(` * This file was auto-generated by generate-api.js.`);
lines.push(` * Do not make direct changes to the file.`);
lines.push(` */`);
lines.push(`import { fetchClient } from '../fetch';`);
lines.push(`import type { FetchOptions } from 'openapi-fetch';`);

// generate sorted imports
const sortedTypes = [...importedTypes].sort();
lines.push(`import type { ${sortedTypes.join(', ')} } from './api';`);
lines.push(``);
lines.push(`export const api = {`);

for (const [groupName, operations] of Object.entries(groups)) {
    lines.push(`    ${groupName}: {`);
    for (const op of operations) {
        lines.push(`        /**`);
        if (op.summary) {
            lines.push(`         * ${op.summary}`);
        }
        lines.push(`         * ${op.method} ${op.route}`);
        lines.push(`         */`);
        lines.push(`        ${op.name}: (${op.params}) =>`);
        lines.push(`            fetchClient.${op.method}('${op.route}', ${op.callArgs} as any),`);
        lines.push(``);
    }
    // remove last trailing blank line inside the group object
    if (lines[lines.length - 1] === '') {
        lines.pop();
    }
    lines.push(`    },`);
}

lines.push(`};`);

const endpointsPath = path.join(outputDir, 'endpoints.ts');
await formatAndWrite(endpointsPath, lines.join('\n') + '\n');
console.log(`Generated ${endpointsPath}`);

console.log('API client generation complete.');
