/**
 * Unified API client codegen script in TypeScript.
 *
 * 1. Backend Spec Export:
 *    The Rust backend uses the `utoipa` and `utoipa-axum` libraries. Handlers
 *    and structs are annotated with macros that compile metadata into an OpenAPI spec.
 *    Command: `cargo run --package app -- export-openapi` exports this JSON spec.
 *
 * 2. File Persistence:
 *    The JSON spec is saved in the workspace root as `openapi.json`.
 *
 * 3. TypeScript Type Generation (Stage 1):
 *    We invoke the programmatic `openapi-typescript` Node.js API to compile
 *    the parsed schemas, routes, and components from `openapi.json` into
 *    strict TypeScript types at `frontend/src/lib/generated/api.d.ts`.
 *
 * 4. TypeScript Wrapper Generation (Stage 2):
 *    This script parses `openapi.json` directly to resolve each route's structure
 *    (method, query parameters, request body). It groups related endpoints by their
 *    base path prefix (e.g. auth, users, health) and outputs a friendly, typed
 *    `api` object at `frontend/src/lib/generated/endpoints.ts`.
 *
 * 5. Prettier Formatting:
 *    Both generated files (`api.d.ts` and `endpoints.ts`) are formatted in-memory
 *    using the programmatic Prettier API before being written to disk, preventing
 *    multiple disk write events and keeping code style consistent.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import prettier from 'prettier';

const __dirname: string = path.dirname(fileURLToPath(import.meta.url));
const openapiPath: string = path.resolve(__dirname, '../../openapi.json');
const outputDir: string = path.join(__dirname, '../src/lib/generated');

interface OperationInfo {
    name: string;
    route: string;
    method: string;
    summary?: string;
    params: string;
    callArgs: string;
}

interface RequestBodyDetails {
    hasBody: boolean;
    bodyRequired: boolean;
    bodyType: string;
}

interface QueryDetails {
    hasQuery: boolean;
    queryRequired: boolean;
}

interface ParamSignatures {
    params: string;
    callArgs: string;
}

async function main(): Promise<void> {
    if (!fs.existsSync(openapiPath)) {
        console.error(`Error: openapi.json not found at ${openapiPath}`);
        process.exit(1);
    }

    fs.mkdirSync(outputDir, { recursive: true });

    try {
        await generateTypes(openapiPath, outputDir);
        await generateEndpoints(openapiPath, outputDir);
        console.log('API client generation complete.');
    } catch (error) {
        console.error('Generation failed:', error);
        process.exit(1);
    }
}

/**
 * Format and write contents to a file path using Prettier settings.
 */
async function formatAndWrite(outputPath: string, content: string): Promise<void> {
    const config = await prettier.resolveConfig(outputPath);
    const formatted = await prettier.format(content, {
        ...config,
        filepath: outputPath,
    });
    fs.writeFileSync(outputPath, formatted, 'utf8');
}

/**
 * Stage 1: Generate type definitions from OpenAPI spec.
 */
async function generateTypes(openapiPath: string, outputDir: string): Promise<void> {
    console.log('Generating TypeScript definitions from OpenAPI spec...');
    const ast = await openapiTS(new URL(`file://${openapiPath}`), {
        rootTypes: true,
        rootTypesNoSchemaPrefix: true,
    });
    const typesContent: string = astToString(ast);
    const typesHeader = `/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n`;
    const typesPath: string = path.join(outputDir, 'api.d.ts');
    await formatAndWrite(typesPath, typesHeader + typesContent);
    console.log(`Generated ${typesPath}`);
}

/**
 * Stage 2: Generate typed endpoint wrappers.
 */
async function generateEndpoints(openapiPath: string, outputDir: string): Promise<void> {
    console.log('Generating TypeScript endpoints...');
    const openapi = JSON.parse(fs.readFileSync(openapiPath, 'utf8'));
    const importedTypes = new Set<string>(['paths']);

    const groups: Record<string, OperationInfo[]> = parseOperations(openapi.paths, importedTypes);
    const fileContent: string = generateEndpointsSource(groups, importedTypes);

    const endpointsPath: string = path.join(outputDir, 'endpoints.ts');
    await formatAndWrite(endpointsPath, fileContent);
    console.log(`Generated ${endpointsPath}`);
}

/**
 * Checks if a method is a standard HTTP method supported by the API client.
 */
function isValidMethod(method: string): boolean {
    return ['get', 'post', 'put', 'delete', 'options', 'head', 'patch', 'trace'].includes(method);
}

/**
 * Parse openapi paths into organized operations grouped by route namespaces.
 */
function parseOperations(
    paths: Record<string, any>,
    importedTypes: Set<string>
): Record<string, OperationInfo[]> {
    const groups: Record<string, OperationInfo[]> = {};
    for (const [route, pathItem] of Object.entries(paths)) {
        for (const [method, operation] of Object.entries(pathItem)) {
            if (!isValidMethod(method)) {
                continue;
            }

            const groupName: string = getGroupName(route);
            if (!groups[groupName]) {
                groups[groupName] = [];
            }

            const processedOp: OperationInfo = processOperation(
                route,
                method,
                operation,
                importedTypes
            );
            groups[groupName].push(processedOp);
        }
    }
    return groups;
}

/**
 * Determine the group name based on the route namespace.
 */
function getGroupName(route: string): string {
    const parts: string[] = route
        .replace(/^\/api/, '')
        .split('/')
        .filter(Boolean);
    let groupName: string = parts[0] || 'general';
    if (groupName === 'api' && parts.length > 1) {
        groupName = parts[1];
    }
    return groupName;
}

/**
 * Process a single operation, returning details required for template rendering.
 */
function processOperation(
    route: string,
    method: string,
    operation: any,
    importedTypes: Set<string>
): OperationInfo {
    const name: string = getOperationName(route, method, operation);
    const bodyDetails: RequestBodyDetails = getRequestBodyDetails(
        route,
        method,
        operation,
        importedTypes
    );
    const queryDetails: QueryDetails = getQueryDetails(operation);
    const { params, callArgs }: ParamSignatures = buildParamSignatures(
        route,
        method,
        bodyDetails,
        queryDetails
    );

    return {
        name,
        route,
        method: method.toUpperCase(),
        summary: operation.summary || operation.description,
        params,
        callArgs,
    };
}

/**
 * Determine the function name for the operation.
 */
function getOperationName(route: string, method: string, operation: any): string {
    if (operation.operationId) {
        return operation.operationId;
    }
    const cleanRoute: string = route
        .replace(/\/api\//g, '')
        .replace(/[^a-zA-Z0-9_/]/g, '')
        .split('/')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
    return method + cleanRoute;
}

/**
 * Extract body specifications and add references to imports.
 */
function getRequestBodyDetails(
    route: string,
    method: string,
    operation: any,
    importedTypes: Set<string>
): RequestBodyDetails {
    const hasBody: boolean =
        operation.requestBody &&
        operation.requestBody.content &&
        operation.requestBody.content['application/json'];

    if (!hasBody) {
        return { hasBody: false, bodyRequired: false, bodyType: '' };
    }

    const bodyRequired: boolean = operation.requestBody.required !== false;
    const schema = operation.requestBody.content['application/json'].schema;
    let bodyType = '';

    if (schema && schema.$ref) {
        const refName: string = schema.$ref.split('/').pop()!;
        bodyType = refName;
        importedTypes.add(refName);
    } else {
        bodyType = `paths['${route}']['${method}']['requestBody']['content']['application/json']`;
    }

    return { hasBody: true, bodyRequired, bodyType };
}

/**
 * Extract query parameters specifications.
 */
function getQueryDetails(operation: any): QueryDetails {
    const queryParams = operation.parameters
        ? operation.parameters.filter((p: any) => p.in === 'query')
        : [];
    const hasQuery: boolean = queryParams.length > 0;
    const queryRequired: boolean = queryParams.some((p: any) => p.required === true);
    return { hasQuery, queryRequired };
}

/**
 * Construct parameter lists and arguments strings for client fetch calls.
 */
function buildParamSignatures(
    route: string,
    method: string,
    bodyDetails: RequestBodyDetails,
    queryDetails: QueryDetails
): ParamSignatures {
    const { hasBody, bodyRequired, bodyType } = bodyDetails;
    const { hasQuery, queryRequired } = queryDetails;
    const paramsList: string[] = [];
    let callArgs = '';

    if (hasBody && hasQuery) {
        paramsList.push(`body${bodyRequired ? '' : '?'}: ${bodyType}`);
        paramsList.push(
            `query${queryRequired ? '' : '?'}: paths['${route}']['${method}']['parameters']['query']`
        );
        paramsList.push(
            `options?: Omit<FetchOptions<paths['${route}']['${method}']>, 'body' | 'params'>`
        );
        callArgs = `{ body, params: { query }, ...options }`;
    } else if (hasBody) {
        paramsList.push(`body${bodyRequired ? '' : '?'}: ${bodyType}`);
        paramsList.push(`options?: Omit<FetchOptions<paths['${route}']['${method}']>, 'body'>`);
        callArgs = `{ body, ...options }`;
    } else if (hasQuery) {
        paramsList.push(
            `query${queryRequired ? '' : '?'}: paths['${route}']['${method}']['parameters']['query']`
        );
        paramsList.push(`options?: Omit<FetchOptions<paths['${route}']['${method}']>, 'params'>`);
        callArgs = `{ params: { query }, ...options }`;
    } else {
        paramsList.push(`options?: FetchOptions<paths['${route}']['${method}']>`);
        callArgs = `options`;
    }

    return {
        params: paramsList.join(', '),
        callArgs,
    };
}

/**
 * Generate string content representing client wrappers.
 */
function generateEndpointsSource(
    groups: Record<string, OperationInfo[]>,
    importedTypes: Set<string>
): string {
    const lines: string[] = [];
    lines.push(`/**`);
    lines.push(` * This file was auto-generated by generate-api.ts.`);
    lines.push(` * Do not make direct changes to the file.`);
    lines.push(` */`);
    lines.push(`import { fetchClient } from '../fetch';`);
    lines.push(`import type { FetchOptions } from 'openapi-fetch';`);

    const sortedTypes: string[] = [...importedTypes].sort();
    lines.push(`import type { ${sortedTypes.join(', ')} } from './api';`);
    lines.push(``);
    lines.push(`export const api = {`);

    for (const [groupName, operations] of Object.entries(groups)) {
        lines.push(`    ${groupName}: {`);
        for (const op of operations) {
            lines.push(`        /**`);
            if (op.summary) {
                lines.push(`         * ${op.summary}`);
            }
            lines.push(`         * ${op.method} ${op.route}`);
            lines.push(`         */`);
            lines.push(`        ${op.name}: (${op.params}) =>`);
            lines.push(
                `            fetchClient.${op.method}('${op.route}', ${op.callArgs} as any),`
            );
            lines.push(``);
        }
        if (lines[lines.length - 1] === '') {
            lines.pop();
        }
        lines.push(`    },`);
    }

    lines.push(`};`);
    return lines.join('\n') + '\n';
}

main();
