[env]
DATABASE_URL = "sqlite:data/db.sqlite"

[alias]
xtask = "run --package xtask --"

[build]
rustc-wrapper = "sccache"

[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]