[server]
host = "0.0.0.0"
port = 3000
log_directives = "info,tower_http=info"

[database]
url = "sqlite:db.sqlite"
max_connections = 10

[jwt]
access_token_expiry = 900    # 15 minutes
refresh_token_expiry = 604800  # 7 days
